<a href="https://colab.research.google.com/github/1krishna173/ai-ml-journey/blob/main/encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import seaborn as sns

In [2]:
df=sns.load_dataset('tips')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [3]:
from sklearn.preprocessing import OneHotEncoder

In [4]:
encoder=OneHotEncoder()

In [11]:
encoded=encoder.fit_transform(df[['sex']])

In [12]:
encoded.toarray()

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.]])

In [17]:
encoder_df=pd.DataFrame(encoded.toarray(),columns=encoder.get_feature_names_out(['sex']))

In [13]:
import pandas as pd

In [18]:
encoder_df

     sex_Female  sex_Male
0           1.0       0.0
1           0.0       1.0
2           0.0       1.0
3           0.0       1.0
4           1.0       0.0
..          ...       ...
239         0.0       1.0
240         1.0       0.0
241         0.0       1.0
242         0.0       1.0
243         1.0       0.0

[244 rows x 2 columns]

In [22]:
df = pd.concat([df, encoder_df], axis=1)

In [23]:
df.head()

   total_bill   tip     sex smoker  day    time  size  sex_Female  sex_Male
0       16.99  1.01  Female     No  Sun  Dinner     2         1.0       0.0
1       10.34  1.66    Male     No  Sun  Dinner     3         0.0       1.0
2       21.01  3.50    Male     No  Sun  Dinner     3         0.0       1.0
3       23.68  3.31    Male     No  Sun  Dinner     2         0.0       1.0
4       24.59  3.61  Female     No  Sun  Dinner     4         1.0       0.0

In [27]:
df.drop('sex',axis=1,inplace=True)

In [28]:
df.head(4)

   total_bill   tip smoker  day    time  size  sex_Female  sex_Male
0       16.99  1.01     No  Sun  Dinner     2         1.0       0.0
1       10.34  1.66     No  Sun  Dinner     3         0.0       1.0
2       21.01  3.50     No  Sun  Dinner     3         0.0       1.0
3       23.68  3.31     No  Sun  Dinner     2         0.0       1.0

In [35]:
encoder_day=encoder.fit_transform(df[['day']])

In [ ]:
encoder_day.toarray()

In [41]:
encoder_day_df=pd.DataFrame(encoder_day.toarray(),columns=encoder.get_feature_names_out(['day']))

In [43]:
df=pd.concat([df,encoder_day_df],axis=1)

In [44]:
df.head(3)

,total_bill,tip,smoker,day,time,size,sex_Female,sex_Male,day_Fri,day_Sat,day_Sun,day_Thur
0,16.99,1.01,No,Sun,Dinner,2,1.0,0.0,0.0,0.0,1.0,0.0
1,10.34,1.66,No,Sun,Dinner,3,0.0,1.0,0.0,0.0,1.0,0.0
2,21.01,3.50,No,Sun,Dinner,3,0.0,1.0,0.0,0.0,1.0,0.0

In [46]:
df.drop('day',axis=1,inplace=True)

In [47]:
df

,total_bill,tip,smoker,time,size,sex_Female,sex_Male,day_Fri,day_Sat,day_Sun,day_Thur
0,16.99,1.01,No,Dinner,2,1.0,0.0,0.0,0.0,1.0,0.0
1,10.34,1.66,No,Dinner,3,0.0,1.0,0.0,0.0,1.0,0.0
2,21.01,3.50,No,Dinner,3,0.0,1.0,0.0,0.0,1.0,0.0
3,23.68,3.31,No,Dinner,2,0.0,1.0,0.0,0.0,1.0,0.0
4,24.59,3.61,No,Dinner,4,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,No,Dinner,3,0.0,1.0,0.0,1.0,0.0,0.0
240,27.18,2.00,Yes,Dinner,2,1.0,0.0,0.0,1.0,0.0,0.0
241,22.67,2.00,Yes,Dinner,2,0.0,1.0,0.0,1.0,0.0,0.0
242,17.82,1.75,No,Dinner,2,0.0,1.0,0.0,1.0,0.0,0.0
243,18.78,3.00,No,Dinner,2,1.0,0.0,0.0,0.0,0.0,1.0

In [48]:
from sklearn.preprocessing import TargetEncoder
Tencoder=TargetEncoder()

In [50]:
df_time=df.groupby('time')['total_bill'].mean().to_dict()

/tmp/ipykernel_5998/3005399276.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_time=df.groupby('time')['total_bill'].mean().to_dict()

In [51]:
df_time

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [52]:
df['time_encoded']=df['time'].map(df_time)

In [53]:
df

,total_bill,tip,smoker,time,size,sex_Female,sex_Male,day_Fri,day_Sat,day_Sun,day_Thur,time_encoded
0,16.99,1.01,No,Dinner,2,1.0,0.0,0.0,0.0,1.0,0.0,20.797159
1,10.34,1.66,No,Dinner,3,0.0,1.0,0.0,0.0,1.0,0.0,20.797159
2,21.01,3.50,No,Dinner,3,0.0,1.0,0.0,0.0,1.0,0.0,20.797159
3,23.68,3.31,No,Dinner,2,0.0,1.0,0.0,0.0,1.0,0.0,20.797159
4,24.59,3.61,No,Dinner,4,1.0,0.0,0.0,0.0,1.0,0.0,20.797159
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,No,Dinner,3,0.0,1.0,0.0,1.0,0.0,0.0,20.797159
240,27.18,2.00,Yes,Dinner,2,1.0,0.0,0.0,1.0,0.0,0.0,20.797159
241,22.67,2.00,Yes,Dinner,2,0.0,1.0,0.0,1.0,0.0,0.0,20.797159
242,17.82,1.75,No,Dinner,2,0.0,1.0,0.0,1.0,0.0,0.0,20.797159
243,18.78,3.00,No,Dinner,2,1.0,0.0,0.0,0.0,0.0,1.0,20.797159

In [55]:
df.drop('time',axis=1,inplace=True)