<a href="https://colab.research.google.com/github/1krishna173/ai-ml-journey/blob/main/Support_vector_Regression_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import seaborn as sns
df=sns.load_dataset('tips')

In [ ]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [ ]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [ ]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [ ]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [ ]:
## We will do the feature enginerring now (OnehotEncoding and labelEncoding)
## befire that we will divide out test and train data so that there is no data leakage

In [ ]:
### Dividing into independent and dependent features
x=df.drop(['total_bill'],axis=1)
y=df['total_bill']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)

In [ ]:
x_train

      tip     sex smoker   day    time  size
114  4.00  Female     No   Sun  Dinner     3
65   3.15    Male     No   Sat  Dinner     3
132  1.50  Female     No  Thur   Lunch     2
207  3.00    Male    Yes   Sat  Dinner     4
162  2.00  Female     No   Sun  Dinner     3
..    ...     ...    ...   ...     ...   ...
106  4.06    Male    Yes   Sat  Dinner     2
14   3.02  Female     No   Sun  Dinner     2
92   1.00  Female    Yes   Fri  Dinner     2
179  3.55    Male    Yes   Sun  Dinner     2
102  2.50  Female    Yes   Sat  Dinner     3

[163 rows x 6 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
le2=LabelEncoder()
le3=LabelEncoder()

In [ ]:
x_train['sex']=le1.fit_transform(x_train['sex'])
x_train['smoker']=le2.fit_transform(x_train['smoker'])
x_train['time']=le3.fit_transform(x_train['time'])

In [ ]:
x_train

      tip  sex  smoker   day  time  size
114  4.00    0       0   Sun     0     3
65   3.15    1       0   Sat     0     3
132  1.50    0       0  Thur     1     2
207  3.00    1       1   Sat     0     4
162  2.00    0       0   Sun     0     3
..    ...  ...     ...   ...   ...   ...
106  4.06    1       1   Sat     0     2
14   3.02    0       0   Sun     0     2
92   1.00    0       1   Fri     0     2
179  3.55    1       1   Sun     0     2
102  2.50    0       1   Sat     0     3

[163 rows x 6 columns]

In [ ]:
x_test['sex']=le1.transform(x_test['sex'])
x_test['smoker']=le2.transform(x_test['smoker'])
x_test['time']=le3.transform(x_test['time'])

In [ ]:
x_test

      tip  sex  smoker   day  time  size
24   3.18    1       0   Sat     0     2
6    2.00    1       0   Sun     0     2
153  2.00    1       0   Sun     0     4
211  5.16    1       1   Sat     0     4
198  2.00    0       1  Thur     1     2
..    ...  ...     ...   ...   ...   ...
180  3.68    1       1   Sun     0     4
5    4.71    1       0   Sun     0     4
56   3.00    1       1   Sat     0     4
125  4.20    0       0  Thur     1     6
148  1.73    1       0  Thur     1     2

[81 rows x 6 columns]

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ct = ColumnTransformer(
    transformers=[
        ('onehot', OneHotEncoder(drop='first'), [3])
    ],
    remainder='passthrough'
)

In [ ]:
x_train=ct.fit_transform(x_train)

In [ ]:
x_test=ct.transform(x_test)

In [ ]:
x_test

array([[1.  , 0.  , 0.  , 3.18, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 0.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 5.16, 1.  , 1.  , 0.  , 4.  ],
       [0.  , 0.  , 1.  , 2.  , 0.  , 1.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 2.56, 1.  , 1.  , 1.  , 2.  ],
       [0.  , 0.  , 1.  , 2.52, 0.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 3.23, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 0.  , 3.  , 0.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 3.  , 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 1.47, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 1.5 , 0.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 1.83, 0.  , 0.  , 1.  , 1.  ],
       [0.  , 0.  , 1.  , 1.36, 0.  , 0.  , 1.  , 3.  ],
       [0.  , 0.  , 1.  , 4.  , 1.  , 1.  , 1.  , 3.  ],
       [0.  , 1.  , 0.  , 3.92, 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.47, 0.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 5.  , 1.  , 0.  , 1.  , 5.  ],
       [1.  , 0.  , 0.  , 2.45, 0.  , 0.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 3.35, 1.  , 0.  , 0.  , 3.  ],
       [1.  , 0.  , 0.  , 4.  , 0.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 1.45, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 3.5 , 0.  , 1.  , 0.  , 3.  ],
       [0.  , 0.  , 1.  , 2.31, 1.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 1.71, 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 5.  , 0.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 0.  , 0.  , 4.  ],
       [0.  , 1.  , 0.  , 5.  , 1.  , 0.  , 0.  , 6.  ],
       [0.  , 1.  , 0.  , 4.  , 1.  , 0.  , 0.  , 3.  ],
       [1.  , 0.  , 0.  , 1.44, 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.34, 1.  , 0.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 3.21, 1.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 3.5 , 0.  , 0.  , 0.  , 3.  ],
       [0.  , 0.  , 1.  , 2.92, 0.  , 0.  , 1.  , 4.  ],
       [0.  , 0.  , 0.  , 1.5 , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 5.  , 0.  , 1.  , 1.  , 4.  ],
       [0.  , 0.  , 1.  , 2.75, 0.  , 0.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 2.  , 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 1.25, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 2.  , 0.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 2.55, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 1.67, 0.  , 0.  , 0.  , 3.  ],
       [0.  , 0.  , 1.  , 2.  , 1.  , 1.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 1.  , 0.  , 1.  , 0.  , 1.  ],
       [1.  , 0.  , 0.  , 1.61, 0.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.31, 1.  , 0.  , 0.  , 3.  ],
       [0.  , 0.  , 1.  , 1.44, 1.  , 0.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 2.72, 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.03, 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 0.  , 4.  , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 4.5 , 1.  , 0.  , 0.  , 4.  ],
       [0.  , 0.  , 1.  , 2.03, 1.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 3.51, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 2.  , 1.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 5.15, 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 1.75, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 2.74, 1.  , 0.  , 0.  , 3.  ],
       [1.  , 0.  , 0.  , 3.  , 1.  , 1.  , 0.  , 3.  ],
       [0.  , 1.  , 0.  , 5.14, 0.  , 0.  , 0.  , 5.  ],
       [0.  , 1.  , 0.  , 3.5 , 0.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 5.65, 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 0.  , 2.5 , 0.  , 1.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 2.01, 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 4.08, 0.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.09, 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 1.  ],
       [1.  , 0.  , 0.  , 3.41, 1.  , 1.  , 0.  , 3.  ],
       [0.  , 1.  , 0.  , 3.48, 1.  , 0.  , 0.  , 3.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 0.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 3.  , 1.  , 1.  , 0.  , 5.  ],
       [0.  , 0.  , 1.  , 2.71, 1.  , 0.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 3.  , 0.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 3.  , 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 3.  , 1.  , 0.  , 0.  , 4.  ],
       [0.  , 1.  , 0.  , 3.68, 1.  , 1.  , 0.  , 4.  ],
       [0.  , 1.  , 0.  , 4.71, 1.  , 0.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 3.  , 1.  , 1.  , 0.  , 4.  ],
       [0.  , 0.  , 1.  , 4.2 , 0.  , 0.  , 1.  , 6.  ],
       [0.  , 0.  , 1.  , 1.73, 1.  , 0.  , 1.  , 2.  ]])

In [ ]:
x_train

array([[0., 1., 0., ..., 0., 0., 3.],
       [1., 0., 0., ..., 0., 0., 3.],
       [0., 0., 1., ..., 0., 1., 2.],
       ...,
       [0., 0., 0., ..., 1., 0., 2.],
       [0., 1., 0., ..., 1., 0., 2.],
       [1., 0., 0., ..., 1., 0., 3.]])

                     Now we will apply the algorithm which is SVR

In [ ]:
from sklearn.svm import SVR
svr=SVR()

In [ ]:
svr.fit(x_train,y_train)

SVR()

In [ ]:
y_pred=svr.predict(x_test)

In [ ]:
from sklearn.metrics import mean_absolute_error,r2_score
mae=mean_absolute_error(y_test,y_pred)
print(mae)
score=r2_score(y_test,y_pred)
print(score)

4.305233267627961
0.49825081042416575

In [ ]:
### HYPERparameter tunning using the grid search cv
from sklearn.model_selection import GridSearchCV
param_grid={
    'C':[0.1,1,10,100],
    'gamma':[1,0.1,0.001,0.00001],
    'kernel':['rbf','linear','poly']

}

In [ ]:
grid=GridSearchCV(svr,param_grid=param_grid,refit=True,verbose=3)
grid.fit(x_train,y_train)

Fitting 5 folds for each of 48 candidates, totalling 240 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.009 total time=   0.0s
[CV 2/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.022 total time=   0.0s
[CV 3/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.034 total time=   0.0s
[CV 4/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.123 total time=   0.0s
[CV 5/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.086 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.482 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.559 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.408 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.502 total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.290 total time=   0.0s
[CV 1/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.032 total time=   0.2s
[CV 2/5] END ......C=0.1, gamma=1, kernel=poly;, score=-0.395 total time=   0.1s
[CV 3/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.448 total time=   0.2s
[CV 4/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.314 total time=   0.2s
[CV 5/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.203 total time=   0.1s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.123 total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.047 total time=   0.0s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.056 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=0.1, kernel=rbf;, score=-0.014 total time=   0.0s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.015 total time=   0.0s
[CV 1/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.482 total time=   0.0s
[CV 2/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.559 total time=   0.0s
[CV 3/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.408 total time=   0.0s
[CV 4/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.502 total time=   0.0s
[CV 5/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.290 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.329 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.416 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.365 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.543 total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.200 total time=   0.0s
[CV 1/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.030 total time=   0.0s
[CV 2/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.041 total time=   0.0s
[CV 3/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.062 total time=   0.0s
[CV 4/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.126 total time=   0.0s
[CV 5/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.111 total time=   0.0s
[CV 1/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.482 total time=   0.0s
[CV 2/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.559 total time=   0.0s
[CV 3/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.408 total time=   0.0s
[CV 4/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.502 total time=   0.0s
[CV 5/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.290 total time=   0.0s
[CV 1/5] END ..C=0.1, gamma=0.001, kernel=poly;, score=-0.036 total time=   0.0s
[CV 2/5] END ..C=0.1, gamma=0.001, kernel=poly;, score=-0.047 total time=   0.0s
[CV 3/5] END ..C=0.1, gamma=0.001, kernel=poly;, score=-0.067 total time=   0.0s
[CV 4/5] END ..C=0.1, gamma=0.001, kernel=poly;, score=-0.134 total time=   0.0s
[CV 5/5] END ..C=0.1, gamma=0.001, kernel=poly;, score=-0.116 total time=   0.0s
[CV 1/5] END ...C=0.1, gamma=1e-05, kernel=rbf;, score=-0.036 total time=   0.0s
[CV 2/5] END ...C=0.1, gamma=1e-05, kernel=rbf;, score=-0.046 total time=   0.0s
[CV 3/5] END ...C=0.1, gamma=1e-05, kernel=rbf;, score=-0.067 total time=   0.0s
[CV 4/5] END ...C=0.1, gamma=1e-05, kernel=rbf;, score=-0.134 total time=   0.0s
[CV 5/5] END ...C=0.1, gamma=1e-05, kernel=rbf;, score=-0.116 total time=   0.0s
[CV 1/5] END .C=0.1, gamma=1e-05, kernel=linear;, score=0.482 total time=   0.0s
[CV 2/5] END .C=0.1, gamma=1e-05, kernel=linear;, score=0.559 total time=   0.0s
[CV 3/5] END .C=0.1, gamma=1e-05, kernel=linear;, score=0.408 total time=   0.0s
[CV 4/5] END .C=0.1, gamma=1e-05, kernel=linear;, score=0.502 total time=   0.0s
[CV 5/5] END .C=0.1, gamma=1e-05, kernel=linear;, score=0.290 total time=   0.0s
[CV 1/5] END ..C=0.1, gamma=1e-05, kernel=poly;, score=-0.036 total time=   0.0s
[CV 2/5] END ..C=0.1, gamma=1e-05, kernel=poly;, score=-0.047 total time=   0.0s
[CV 3/5] END ..C=0.1, gamma=1e-05, kernel=poly;, score=-0.067 total time=   0.0s
[CV 4/5] END ..C=0.1, gamma=1e-05, kernel=poly;, score=-0.134 total time=   0.0s
[CV 5/5] END ..C=0.1, gamma=1e-05, kernel=poly;, score=-0.116 total time=   0.0s
[CV 1/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.221 total time=   0.0s
[CV 2/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.159 total time=   0.0s
[CV 3/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.123 total time=   0.0s
[CV 4/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.012 total time=   0.0s
[CV 5/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.138 total time=   0.0s
[CV 1/5] END .......C=1, gamma=1, kernel=linear;, score=0.437 total time=   0.0s
[CV 2/5] END .......C=1, gamma=1, kernel=linear;, score=0.563 total time=   0.0s
[CV 3/5] END .......C=1, gamma=1, kernel=linear;, score=0.420 total time=   0.0s
[CV 4/5] END .......C=1, gamma=1, kernel=linear;, score=0.524 total time=   0.0s
[CV 5/5] END .......C=1, gamma=1, kernel=linear;, score=0.321 total time=   0.0s
[CV 1/5] END ........C=1, gamma=1, kernel=poly;, score=-0.091 total time=   1.7s
[CV 2/5] END ........C=1, gamma=1, kernel=poly;, score=-0.558 total time=   1.0s
[CV 3/5] END .........C=1, gamma=1, kernel=poly;, score=0.368 total time=   2.0s
[CV 4/5] END .........C=1, gamma=1, kernel=poly;, score=0.170 total time=   4.2s
[CV 5/5] END .........C=1, gamma=1, kernel=poly;, score=0.121 total time=   2.1s
[CV 1/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.531 total time=   0.0s
[CV 2/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.371 total time=   0.0s
[CV 3/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.385 total time=   0.0s
[CV 4/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.301 total time=   0.0s
[CV 5/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.281 total time=   0.0s
[CV 1/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.437 total time=   0.0s
[CV 2/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.563 total time=   0.0s
[CV 3/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.420 total time=   0.0s
[CV 4/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.524 total time=   0.0s
[CV 5/5] END .....C=1, gamma=0.1, kernel=linear;, score=0.321 total time=   0.0s
[CV 1/5] END .......C=1, gamma=0.1, kernel=poly;, score=0.336 total time=   0.0s
[CV 2/5] END .......C=1, gamma=0.1, kernel=poly;, score=0.206 total time=   0.0s
[CV 3/5] END .......C=1, gamma=0.1, kernel=poly;, score=0.395 total time=   0.0s
[CV 4/5] END .......C=1, gamma=0.1, kernel=poly;, score=0.550 total time=   0.0s
[CV 5/5] END .......C=1, gamma=0.1, kernel=poly;, score=0.309 total time=   0.0s
[CV 1/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.023 total time=   0.0s
[CV 2/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.008 total time=   0.0s
[CV 3/5] END .....C=1, gamma=0.001, kernel=rbf;, score=-0.014 total time=   0.0s
[CV 4/5] END .....C=1, gamma=0.001, kernel=rbf;, score=-0.058 total time=   0.0s
[CV 5/5] END .....C=1, gamma=0.001, kernel=rbf;, score=-0.064 total time=   0.0s
[CV 1/5] END ...C=1, gamma=0.001, kernel=linear;, score=0.437 total time=   0.0s
[CV 2/5] END ...C=1, gamma=0.001, kernel=linear;, score=0.563 total time=   0.0s
[CV 3/5] END ...C=1, gamma=0.001, kernel=linear;, score=0.420 total time=   0.0s
[CV 4/5] END ...C=1, gamma=0.001, kernel=linear;, score=0.524 total time=   0.0s
[CV 5/5] END ...C=1, gamma=0.001, kernel=linear;, score=0.321 total time=   0.0s
[CV 1/5] END ....C=1, gamma=0.001, kernel=poly;, score=-0.036 total time=   0.0s
[CV 2/5] END ....C=1, gamma=0.001, kernel=poly;, score=-0.046 total time=   0.0s
[CV 3/5] END ....C=1, gamma=0.001, kernel=poly;, score=-0.067 total time=   0.0s
[CV 4/5] END ....C=1, gamma=0.001, kernel=poly;, score=-0.134 total time=   0.0s
[CV 5/5] END ....C=1, gamma=0.001, kernel=poly;, score=-0.116 total time=   0.0s
[CV 1/5] END .....C=1, gamma=1e-05, kernel=rbf;, score=-0.035 total time=   0.0s
[CV 2/5] END .....C=1, gamma=1e-05, kernel=rbf;, score=-0.046 total time=   0.0s
[CV 3/5] END .....C=1, gamma=1e-05, kernel=rbf;, score=-0.066 total time=   0.0s
[CV 4/5] END .....C=1, gamma=1e-05, kernel=rbf;, score=-0.133 total time=   0.0s
[CV 5/5] END .....C=1, gamma=1e-05, kernel=rbf;, score=-0.115 total time=   0.0s
[CV 1/5] END ...C=1, gamma=1e-05, kernel=linear;, score=0.437 total time=   0.0s
[CV 2/5] END ...C=1, gamma=1e-05, kernel=linear;, score=0.563 total time=   0.0s
[CV 3/5] END ...C=1, gamma=1e-05, kernel=linear;, score=0.420 total time=   0.0s
[CV 4/5] END ...C=1, gamma=1e-05, kernel=linear;, score=0.524 total time=   0.0s
[CV 5/5] END ...C=1, gamma=1e-05, kernel=linear;, score=0.321 total time=   0.0s
[CV 1/5] END ....C=1, gamma=1e-05, kernel=poly;, score=-0.036 total time=   0.0s
[CV 2/5] END ....C=1, gamma=1e-05, kernel=poly;, score=-0.047 total time=   0.0s
[CV 3/5] END ....C=1, gamma=1e-05, kernel=poly;, score=-0.067 total time=   0.0s
[CV 4/5] END ....C=1, gamma=1e-05, kernel=poly;, score=-0.134 total time=   0.0s
[CV 5/5] END ....C=1, gamma=1e-05, kernel=poly;, score=-0.116 total time=   0.0s
[CV 1/5] END .........C=10, gamma=1, kernel=rbf;, score=0.371 total time=   0.0s
[CV 2/5] END .........C=10, gamma=1, kernel=rbf;, score=0.498 total time=   0.0s
[CV 3/5] END .........C=10, gamma=1, kernel=rbf;, score=0.408 total time=   0.0s
[CV 4/5] END .........C=10, gamma=1, kernel=rbf;, score=0.137 total time=   0.0s
[CV 5/5] END .........C=10, gamma=1, kernel=rbf;, score=0.391 total time=   0.0s
[CV 1/5] END ......C=10, gamma=1, kernel=linear;, score=0.445 total time=   0.0s
[CV 2/5] END ......C=10, gamma=1, kernel=linear;, score=0.575 total time=   0.0s
[CV 3/5] END ......C=10, gamma=1, kernel=linear;, score=0.435 total time=   0.0s
[CV 4/5] END ......C=10, gamma=1, kernel=linear;, score=0.508 total time=   0.0s
[CV 5/5] END ......C=10, gamma=1, kernel=linear;, score=0.313 total time=   0.0s
[CV 1/5] END .......C=10, gamma=1, kernel=poly;, score=-1.448 total time=  16.0s
[CV 2/5] END .......C=10, gamma=1, kernel=poly;, score=-0.203 total time=   7.8s
[CV 3/5] END ........C=10, gamma=1, kernel=poly;, score=0.153 total time=   9.2s
[CV 4/5] END ........C=10, gamma=1, kernel=poly;, score=0.051 total time=  12.0s
[CV 5/5] END .......C=10, gamma=1, kernel=poly;, score=-1.559 total time=  12.6s
[CV 1/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.520 total time=   0.0s
[CV 2/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.564 total time=   0.0s
[CV 3/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.441 total time=   0.0s
[CV 4/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.445 total time=   0.0s
[CV 5/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.374 total time=   0.0s
[CV 1/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.445 total time=   0.0s
[CV 2/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.575 total time=   0.0s
[CV 3/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.435 total time=   0.0s
[CV 4/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.508 total time=   0.0s
[CV 5/5] END ....C=10, gamma=0.1, kernel=linear;, score=0.313 total time=   0.0s
[CV 1/5] END ......C=10, gamma=0.1, kernel=poly;, score=0.203 total time=   0.0s
[CV 2/5] END .....C=10, gamma=0.1, kernel=poly;, score=-0.209 total time=   0.0s
[CV 3/5] END ......C=10, gamma=0.1, kernel=poly;, score=0.411 total time=   0.0s
[CV 4/5] END ......C=10, gamma=0.1, kernel=poly;, score=0.518 total time=   0.0s
[CV 5/5] END ......C=10, gamma=0.1, kernel=poly;, score=0.335 total time=   0.0s
[CV 1/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.334 total time=   0.0s
[CV 2/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.298 total time=   0.0s
[CV 3/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.248 total time=   0.0s
[CV 4/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.283 total time=   0.0s
[CV 5/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.150 total time=   0.0s
[CV 1/5] END ..C=10, gamma=0.001, kernel=linear;, score=0.445 total time=   0.0s
[CV 2/5] END ..C=10, gamma=0.001, kernel=linear;, score=0.575 total time=   0.0s
[CV 3/5] END ..C=10, gamma=0.001, kernel=linear;, score=0.435 total time=   0.0s
[CV 4/5] END ..C=10, gamma=0.001, kernel=linear;, score=0.508 total time=   0.0s
[CV 5/5] END ..C=10, gamma=0.001, kernel=linear;, score=0.313 total time=   0.0s
[CV 1/5] END ...C=10, gamma=0.001, kernel=poly;, score=-0.034 total time=   0.0s
[CV 2/5] END ...C=10, gamma=0.001, kernel=poly;, score=-0.044 total time=   0.0s
[CV 3/5] END ...C=10, gamma=0.001, kernel=poly;, score=-0.065 total time=   0.0s
[CV 4/5] END ...C=10, gamma=0.001, kernel=poly;, score=-0.131 total time=   0.0s
[CV 5/5] END ...C=10, gamma=0.001, kernel=poly;, score=-0.115 total time=   0.0s
[CV 1/5] END ....C=10, gamma=1e-05, kernel=rbf;, score=-0.030 total time=   0.0s
[CV 2/5] END ....C=10, gamma=1e-05, kernel=rbf;, score=-0.041 total time=   0.0s
[CV 3/5] END ....C=10, gamma=1e-05, kernel=rbf;, score=-0.062 total time=   0.0s
[CV 4/5] END ....C=10, gamma=1e-05, kernel=rbf;, score=-0.126 total time=   0.0s
[CV 5/5] END ....C=10, gamma=1e-05, kernel=rbf;, score=-0.111 total time=   0.0s
[CV 1/5] END ..C=10, gamma=1e-05, kernel=linear;, score=0.445 total time=   0.0s
[CV 2/5] END ..C=10, gamma=1e-05, kernel=linear;, score=0.575 total time=   0.0s
[CV 3/5] END ..C=10, gamma=1e-05, kernel=linear;, score=0.435 total time=   0.0s
[CV 4/5] END ..C=10, gamma=1e-05, kernel=linear;, score=0.508 total time=   0.0s
[CV 5/5] END ..C=10, gamma=1e-05, kernel=linear;, score=0.313 total time=   0.0s
[CV 1/5] END ...C=10, gamma=1e-05, kernel=poly;, score=-0.036 total time=   0.0s
[CV 2/5] END ...C=10, gamma=1e-05, kernel=poly;, score=-0.047 total time=   0.0s
[CV 3/5] END ...C=10, gamma=1e-05, kernel=poly;, score=-0.067 total time=   0.0s
[CV 4/5] END ...C=10, gamma=1e-05, kernel=poly;, score=-0.134 total time=   0.0s
[CV 5/5] END ...C=10, gamma=1e-05, kernel=poly;, score=-0.116 total time=   0.0s
[CV 1/5] END ........C=100, gamma=1, kernel=rbf;, score=0.297 total time=   0.0s
[CV 2/5] END ........C=100, gamma=1, kernel=rbf;, score=0.600 total time=   0.0s
[CV 3/5] END ........C=100, gamma=1, kernel=rbf;, score=0.469 total time=   0.0s
[CV 4/5] END .......C=100, gamma=1, kernel=rbf;, score=-0.077 total time=   0.0s
[CV 5/5] END .......C=100, gamma=1, kernel=rbf;, score=-0.037 total time=   0.0s
[CV 1/5] END .....C=100, gamma=1, kernel=linear;, score=0.461 total time=   0.0s
[CV 2/5] END .....C=100, gamma=1, kernel=linear;, score=0.578 total time=   0.0s
[CV 3/5] END .....C=100, gamma=1, kernel=linear;, score=0.432 total time=   0.0s
[CV 4/5] END .....C=100, gamma=1, kernel=linear;, score=0.509 total time=   0.0s
[CV 5/5] END .....C=100, gamma=1, kernel=linear;, score=0.310 total time=   0.0s
[CV 1/5] END .....C=100, gamma=1, kernel=poly;, score=-20.655 total time= 3.0min
[CV 2/5] END .......C=100, gamma=1, kernel=poly;, score=0.426 total time=  41.8s
[CV 3/5] END ......C=100, gamma=1, kernel=poly;, score=-0.296 total time= 1.9min
[CV 4/5] END ......C=100, gamma=1, kernel=poly;, score=-0.002 total time= 4.4min
[CV 5/5] END ......C=100, gamma=1, kernel=poly;, score=-3.705 total time= 1.1min
[CV 1/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.316 total time=   0.0s
[CV 2/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.643 total time=   0.0s
[CV 3/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.437 total time=   0.0s
[CV 4/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.200 total time=   0.0s
[CV 5/5] END ......C=100, gamma=0.1, kernel=rbf;, score=0.418 total time=   0.0s
[CV 1/5] END ...C=100, gamma=0.1, kernel=linear;, score=0.461 total time=   0.0s
[CV 2/5] END ...C=100, gamma=0.1, kernel=linear;, score=0.578 total time=   0.0s
[CV 3/5] END ...C=100, gamma=0.1, kernel=linear;, score=0.432 total time=   0.0s
[CV 4/5] END ...C=100, gamma=0.1, kernel=linear;, score=0.509 total time=   0.0s
[CV 5/5] END ...C=100, gamma=0.1, kernel=linear;, score=0.310 total time=   0.1s
[CV 1/5] END .....C=100, gamma=0.1, kernel=poly;, score=0.032 total time=   0.2s
[CV 2/5] END ....C=100, gamma=0.1, kernel=poly;, score=-0.396 total time=   0.1s
[CV 3/5] END .....C=100, gamma=0.1, kernel=poly;, score=0.448 total time=   0.1s
[CV 4/5] END .....C=100, gamma=0.1, kernel=poly;, score=0.314 total time=   0.2s
[CV 5/5] END .....C=100, gamma=0.1, kernel=poly;, score=0.203 total time=   0.1s
[CV 1/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.477 total time=   0.0s
[CV 2/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.585 total time=   0.0s
[CV 3/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.421 total time=   0.0s
[CV 4/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.528 total time=   0.0s
[CV 5/5] END ....C=100, gamma=0.001, kernel=rbf;, score=0.297 total time=   0.0s
[CV 1/5] END .C=100, gamma=0.001, kernel=linear;, score=0.461 total time=   0.0s
[CV 2/5] END .C=100, gamma=0.001, kernel=linear;, score=0.578 total time=   0.0s
[CV 3/5] END .C=100, gamma=0.001, kernel=linear;, score=0.432 total time=   0.0s
[CV 4/5] END .C=100, gamma=0.001, kernel=linear;, score=0.509 total time=   0.0s
[CV 5/5] END .C=100, gamma=0.001, kernel=linear;, score=0.310 total time=   0.1s
[CV 1/5] END ..C=100, gamma=0.001, kernel=poly;, score=-0.021 total time=   0.0s
[CV 2/5] END ..C=100, gamma=0.001, kernel=poly;, score=-0.025 total time=   0.0s
[CV 3/5] END ..C=100, gamma=0.001, kernel=poly;, score=-0.050 total time=   0.0s
[CV 4/5] END ..C=100, gamma=0.001, kernel=poly;, score=-0.106 total time=   0.0s
[CV 5/5] END ..C=100, gamma=0.001, kernel=poly;, score=-0.104 total time=   0.0s
[CV 1/5] END ....C=100, gamma=1e-05, kernel=rbf;, score=0.024 total time=   0.0s
[CV 2/5] END ....C=100, gamma=1e-05, kernel=rbf;, score=0.009 total time=   0.0s
[CV 3/5] END ...C=100, gamma=1e-05, kernel=rbf;, score=-0.013 total time=   0.0s
[CV 4/5] END ...C=100, gamma=1e-05, kernel=rbf;, score=-0.056 total time=   0.0s
[CV 5/5] END ...C=100, gamma=1e-05, kernel=rbf;, score=-0.063 total time=   0.0s
[CV 1/5] END .C=100, gamma=1e-05, kernel=linear;, score=0.461 total time=   0.0s
[CV 2/5] END .C=100, gamma=1e-05, kernel=linear;, score=0.578 total time=   0.0s
[CV 3/5] END .C=100, gamma=1e-05, kernel=linear;, score=0.432 total time=   0.0s
[CV 4/5] END .C=100, gamma=1e-05, kernel=linear;, score=0.509 total time=   0.0s
[CV 5/5] END .C=100, gamma=1e-05, kernel=linear;, score=0.310 total time=   0.1s
[CV 1/5] END ..C=100, gamma=1e-05, kernel=poly;, score=-0.036 total time=   0.0s
[CV 2/5] END ..C=100, gamma=1e-05, kernel=poly;, score=-0.047 total time=   0.0s
[CV 3/5] END ..C=100, gamma=1e-05, kernel=poly;, score=-0.067 total time=   0.0s
[CV 4/5] END ..C=100, gamma=1e-05, kernel=poly;, score=-0.134 total time=   0.0s
[CV 5/5] END ..C=100, gamma=1e-05, kernel=poly;, score=-0.116 total time=   0.0s

GridSearchCV(estimator=SVR(),
             param_grid={'C': [0.1, 1, 10, 100],
                         'gamma': [1, 0.1, 0.001, 1e-05],
                         'kernel': ['rbf', 'linear', 'poly']},
             verbose=3)

In [90]:
grid.best_params_

{'C': 10, 'gamma': 0.1, 'kernel': 'rbf'}

In [91]:
grid_prediction=grid.predict(x_test)

In [92]:
from sklearn.metrics import mean_absolute_error,r2_score
mae=mean_absolute_error(y_test,grid_prediction)
print(mae)
score=r2_score(y_test,grid_prediction)
print(score)

4.0678529248029065
0.5701046240467684